apiVersion: v1
kind: Secret
metadata:
  name: ftps-login
stringData:
  user: ftpsuser
  password: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: ftps-login
              key: user
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps-login
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: sharingkey
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps-port
  - port: 20
    name: ftps-data
  - port: 30000
    name: psva-data
  type: LoadBalancer